### ISSUE TITLE
xmlpak-Re not install on KernelSU 

### ISSUE THREAD

**Issue by pacmankillers** [Magisk-Modules-Alt-Repo/xmlpak-RE#1]
Hi, i tried to install xmlpak in my device with KernelSU but a message appears

"Error: Specified file not found in archive"

![Screenshot_2023-07-31-23-46-15-899](https://github.com/Magisk-Modules-Alt-Repo/xmlpak-RE/assets/19720291/abac361b-bb96-45b8-8493-3fc871686ac0)

**Comment by rushiranpise** [comment]
Make sure you install correct zip!
Download from [here](https://github.com/rushiranpise/xmlpak-RE/releases)
