### ISSUE TITLE
Samsung apps stop working on OnePlus 8 Pro

### ISSUE THREAD

**Issue by b0l5** [Magisk-Modules-Alt-Repo/xmlpak-RE#2]
Hello, I have OnePlus 8 Pro IN2023_13 1.0582(EX01).

I install XMLPack-RE, then I turn on airplane mode, stop Play store and Services Google Apps and clear all cache. After reboot my Samsung apps stop working (Galaxy Wearable, Samsung Health, Galaxy Watch 6 Manager).

**Comment by rushiranpise** [comment]
which was the last version they were working with original xmlpak, or they were working without xmlpak

**Comment by b0l5** [comment]
if I turn off your XMLPack, then apps work fine. 
I think that oryginał XMLPack dosent work on A13, so I don't use them, and few days ago I installed yours.

**Comment by rushiranpise** [comment]
Were these apps working before without module? If yes, go to the module folder system/etc/xmlpak-re.xml and search for samsung and delete all lines in samsung section, save and reboot

**Comment by b0l5** [comment]
> Were these apps working before without module? If yes, go to the module folder system/etc/xmlpak-re.xml and search for samsung and delete all lines in samsung section, save and reboot 

Yes, they works before.

Ok, i found file on system/etc/premission and I deleted those Samsung lines, and do reboot. Now all apps work fine. 

But, when you add new update in future of xmlpak, I must again delete those lines, or you find solution of that?

**Comment by friday06** [comment]
This thing also Happens on Ported App of Samsung, I've been using Samsung music port, everything is working well and good without the module installed nd it starts crashing after installing. ( Fixed After disabling Samsung Section in The module)

**Comment by rushiranpise** [comment]
can you check with 8.5

**Comment by ohayoubaka** [comment]
> can you check with 8.5

Just installed 8.5, looks like Galaxy Wearable app still crashes unfortunately

**Comment by b0l5** [comment]
> > can you check with 8.5
> 
> Just installed 8.5, looks like Galaxy Wearable app still crashes unfortunately

yes, I have this same after update

**Comment by rushiranpise** [comment]
Okay samsung galaxy app is crashing for me too, @friday06  can you share the music port

**Comment by rushiranpise** [comment]
check with this build https://github.com/rushiranpise/xmlpak-RE/releases/download/v8.5-49/xmlpak-RE_module_v8.5.zip

**Comment by b0l5** [comment]
> check with this build https://github.com/rushiranpise/xmlpak-RE/releases/download/v8.5-49/xmlpak-RE_module_v8.5.zip

Samsung apps works!

**Comment by ohayoubaka** [comment]
> check with this build https://github.com/rushiranpise/xmlpak-RE/releases/download/v8.5-49/xmlpak-RE_module_v8.5.zip

Can confirm Galaxy Wearable app no longer crashes with this build 👍

**Comment by rushiranpise** [comment]
Will be fixed in next version
