### ISSUE TITLE
 bootloop in v8.0

### ISSUE THREAD

**Issue by snookilow** [Magisk-Modules-Alt-Repo/xmlpak-RE#3]
In version 8.0 on Samsung note 20 (Android11) - bootloop. On version 6.0 everything is fine

**Comment by rushiranpise** [comment]
have you tried other versions like 6.5,7.0,7.5 ?

**Comment by rushiranpise** [comment]
can you check with 8.5

**Comment by snookilow** [comment]
> can you check with 8.5

8.5 - bootloop 
7.5 - bootloop 
7.0 - bootloop 
6.5 - is good
6.0 - is good

After 6.5 something went wrong then
To fix this, I’ll check any versions; it’s not difficult for me
My device - Samsung note 20 [Exynos](  (Android 11) Magisk 23 (without zygote)
Maybe the problem is that need Magisk 24+? (but I won’t switch to 24 so I won’t be able to check)

**Comment by rushiranpise** [comment]
no nothing to do with magisk verison, i,ll check

**Comment by rushiranpise** [comment]
try this https://github.com/rushiranpise/xmlpak-RE/releases/download/v8.5-48/xmlpak-RE_module_v8.5.zip

**Comment by snookilow** [comment]
> try this

I tried it again and it didn't help - bootloop :(

**Comment by rushiranpise** [comment]
> > try this
> 
> I tried it again and it didn't help - bootloop :(

strange, i have removed almost all possible features which can lead to bootloop.
make sure you flash the correct zip

**Comment by rushiranpise** [comment]
check with this build https://github.com/rushiranpise/xmlpak-RE/releases/download/v8.5-49/xmlpak-RE_module_v8.5.zip

**Comment by snookilow** [comment]
> sure you flash the correct zip

You can be sure that I am flashing a new file and not an old one

**Comment by snookilow** [comment]
> check with this build https://github.com/rushiranpise/xmlpak-RE/releases/download/v8.5-49/xmlpak-RE_module_v8.5.zip

Bro it's a bootloop again T___T

**Comment by snookilow** [comment]
We can call Discord and I’ll show you via webcam that I don’t lie

**Comment by rushiranpise** [comment]
Message me on telegram @rushi_ranpise
